package com.net
{
    import com.game.activities.handler.*;
    import com.game.activities.message.*;
    import com.game.activitiesoverview.handler.*;
    import com.game.activitiesoverview.message.*;
    import com.game.arrow.handler.*;
    import com.game.arrow.message.*;
    import com.game.artifact.handler.*;
    import com.game.artifact.message.*;
    import com.game.assistant.message.*;
    import com.game.auction.handler.*;
    import com.game.auction.message.*;
    import com.game.autopk.handler.*;
    import com.game.backpack.handler.*;
    import com.game.backpack.message.*;
    import com.game.bag.handler.*;
    import com.game.bag.message.*;
    import com.game.bank.handler.*;
    import com.game.bank.message.*;
    import com.game.batter.handler.*;
    import com.game.batter.message.*;
    import com.game.biwudao.handler.*;
    import com.game.biwudao.message.*;
    import com.game.bocake.message.*;
    import com.game.bosshome.message.*;
    import com.game.bossrank.handler.*;
    import com.game.buff.handler.*;
    import com.game.buff.message.*;
    import com.game.card.handler.*;
    import com.game.card.message.*;
    import com.game.casting.handler.*;
    import com.game.casting.message.*;
    import com.game.challenge.handler.*;
    import com.game.challenge.message.*;
    import com.game.chat.handler.*;
    import com.game.chat.message.*;
    import com.game.chestbox.handler.*;
    import com.game.chestbox.message.*;
    import com.game.cloudbuy.handler.*;
    import com.game.cloudbuy.message.*;
    import com.game.collect.handler.*;
    import com.game.collect.message.*;
    import com.game.country.handler.*;
    import com.game.country.message.*;
    import com.game.dataserver.handler.*;
    import com.game.dataserver.message.*;
    import com.game.dazuo.handler.*;
    import com.game.dazuo.message.*;
    import com.game.dianjiangchun.handler.*;
    import com.game.dianjiangchun.message.*;
    import com.game.elementHeart.handler.*;
    import com.game.epalace.handler.*;
    import com.game.epalace.message.*;
    import com.game.equip.handler.*;
    import com.game.equip.message.*;
    import com.game.equipstreng.handler.*;
    import com.game.equipstreng.message.*;
    import com.game.expireguide.handler.*;
    import com.game.fight.handler.*;
    import com.game.fight.message.*;
    import com.game.fightpower.handler.*;
    import com.game.fightpower.message.*;
    import com.game.friend.handler.*;
    import com.game.friend.message.*;
    import com.game.gem.handler.*;
    import com.game.gem.message.*;
    import com.game.gift.handler.*;
    import com.game.gift.message.*;
    import com.game.gm.handler.*;
    import com.game.gm.message.*;
    import com.game.goldRaffle.handler.*;
    import com.game.goldRaffle.message.*;
    import com.game.gradegift.handler.*;
    import com.game.gradegift.message.*;
    import com.game.grandMasterPanel.handler.*;
    import com.game.guard.message.*;
    import com.game.guide.handler.*;
    import com.game.guild.handler.*;
    import com.game.guild.message.*;
    import com.game.guildflag.handler.*;
    import com.game.guildflag.message.*;
    import com.game.hiddenweapon.handler.*;
    import com.game.hiddenweapon.message.*;
    import com.game.horse.handler.*;
    import com.game.horse.message.*;
    import com.game.horseweapon.handler.*;
    import com.game.horseweapon.message.*;
    import com.game.login.handler.*;
    import com.game.login.message.*;
    import com.game.longyuan.handler.*;
    import com.game.longyuan.message.*;
    import com.game.lostskills.handler.*;
    import com.game.lostskills.message.*;
    import com.game.magicbook.handler.*;
    import com.game.magicbook.message.*;
    import com.game.mail.handler.*;
    import com.game.mail.message.*;
    import com.game.map.handler.*;
    import com.game.map.message.*;
    import com.game.masterequip.message.*;
    import com.game.masterskill.message.*;
    import com.game.maze.handler.*;
    import com.game.maze.message.*;
    import com.game.melting.handler.*;
    import com.game.melting.message.*;
    import com.game.monster.handler.*;
    import com.game.monster.message.*;
    import com.game.newactivity.handler.*;
    import com.game.newactivity.message.*;
    import com.game.npc.handler.*;
    import com.game.npc.message.*;
    import com.game.offline.handler.*;
    import com.game.offline.message.*;
    import com.game.perfectInfo.handler.*;
    import com.game.pet.handler.*;
    import com.game.pet.message.*;
    import com.game.player.handler.*;
    import com.game.player.message.*;
    import com.game.plugset.handler.*;
    import com.game.plugset.message.*;
    import com.game.pray.message.*;
    import com.game.prey.handler.*;
    import com.game.prompt.handler.*;
    import com.game.prompt.message.*;
    import com.game.protect.handler.*;
    import com.game.protect.message.*;
    import com.game.protectAdvanced.message.*;
    import com.game.publogin.handler.*;
    import com.game.publogin.message.*;
    import com.game.rank.handler.*;
    import com.game.rank.message.*;
    import com.game.realm.handler.*;
    import com.game.realm.message.*;
    import com.game.redfortress.handler.*;
    import com.game.redfortress.message.*;
    import com.game.remark.handler.*;
    import com.game.scripts.handler.*;
    import com.game.scripts.message.*;
    import com.game.server.handler.*;
    import com.game.server.message.*;
    import com.game.setupmenu.handler.*;
    import com.game.setupmenu.message.*;
    import com.game.shop.handler.*;
    import com.game.shop.message.*;
    import com.game.shortcut.handler.*;
    import com.game.shortcut.message.*;
    import com.game.signwage.handler.*;
    import com.game.signwage.message.*;
    import com.game.skill.handler.*;
    import com.game.skill.message.*;
    import com.game.spirittree.handler.*;
    import com.game.spirittree.message.*;
    import com.game.stalls.handler.*;
    import com.game.stalls.message.*;
    import com.game.store.handler.*;
    import com.game.store.message.*;
    import com.game.summonpet.handler.*;
    import com.game.summonpet.message.*;
    import com.game.supervip.handler.*;
    import com.game.supervip.message.*;
    import com.game.task.handler.*;
    import com.game.task.message.*;
    import com.game.team.handler.*;
    import com.game.team.message.*;
    import com.game.titleNotice.handler.*;
    import com.game.toplist.handler.*;
    import com.game.toplist.message.*;
    import com.game.transactions.handler.*;
    import com.game.transactions.message.*;
    import com.game.version.handler.*;
    import com.game.version.message.*;
    import com.game.vip.handler.*;
    import com.game.vip.message.*;
    import com.game.wine.handler.*;
    import com.game.wine.message.*;
    import com.game.worldlevel.handler.*;
    import com.game.worldlevel.message.*;
    import com.game.ybcard.handler.*;
    import com.game.ybcard.message.*;
    import com.game.zones.handler.*;
    import com.game.zones.message.*;
    import flash.utils.*;
    import interfaces.net.*;
    import net.*;

    public class MessagePool extends Object implements IMessagePool
    {
        private var messages:Dictionary;
        private var handlers:Dictionary;

        public function MessagePool()
        {
            this.messages = new Dictionary();
            this.handlers = new Dictionary();
            this.register(122101, ResTransactionsLaunchMessage, ResTransactionsLaunchHandler);
            this.register(122102, ResTransactionsCanceledMessage, ResTransactionsCanceledHandler);
            this.register(122103, ResTransactionsStartMessage, ResTransactionsStartHandler);
            this.register(122104, ResTransactionsIntoItemMessage, ResTransactionsIntoItemHandler);
            this.register(122105, ResTransactionsRemoveItemMessage, ResTransactionsRemoveItemHandler);
            this.register(122106, ResTransactionsChangeGoldMessage, ResTransactionsChangeGoldHandler);
            this.register(122107, ResTransactionsChangeYuanbaoMessage, ResTransactionsChangeYuanbaoHandler);
            this.register(122108, ResTransactionsSetStateMessage, ResTransactionsSetStateHandler);
            this.register(122109, ResTransactionsSuccessMessage, ResTransactionsSuccessHandler);
            this.register(122110, ResCanreceiveYuanbaoMessage, ResCanreceiveYuanbaoHandler);
            this.register(104101, ResItemInfosMessage, ResItemInfosHandler);
            this.register(104102, ResItemAddMessage, ResItemAddHandler);
            this.register(104103, ResItemChangeMessage, ResItemChangeHandler);
            this.register(104104, ResItemRemoveMessage, ResItemRemoveHandler);
            this.register(104105, ResMoneyChangeMessage, ResMoneyChangeHandler);
            this.register(104106, ResGoldChangeMessage, ResGoldChangeHandler);
            this.register(104107, ResUseItemSuccessMessage, ResUseItemSuccessHandler);
            this.register(104108, ResOpenCellInfoMessage, ResOpenCellInfoHandler);
            this.register(104109, ResCellTimeMessage, ResCellTimeHandler);
            this.register(104110, ResOpenCellResultMessage, ResOpenCellResultHandler);
            this.register(104111, ResBindGoldChangeMessage, ResBindGoldChangeHandler);
            this.register(113101, ResBuffsMessage, ResBuffsHandler);
            this.register(113102, ResAddBuffMessage, ResAddBuffHandler);
            this.register(576001, ResDoubleExpSetBuffMessage, ResDoubleExpSetBuffHandler);
            this.register(113103, ResRemoveBuffMessage, ResRemoveBuffHandler);
            this.register(113104, ResBuffInfoMessage, ResBuffInfoHandler);
            this.register(111101, ChatResponseMessage, ChatResponseHandler);
            this.register(111102, RoleQueryResultMessage, RoleQueryResultHandler);
            this.register(116101, SendDianjiangchunInfoToClientMessage, SendDianjiangchunInfoToClientHandler);
            this.register(106101, WearEquipItemMessage, WearEquipItemHandler);
            this.register(106102, UnwearEquipItemMessage, UnwearEquipItemHandler);
            this.register(102101, ResFightBroadcastMessage, ResFightBroadcastHandler);
            this.register(102102, ResAttackResultMessage, ResAttackResultHandler);
            this.register(102103, ResAttackRangeMessage, ResAttackRangeHandler);
            this.register(119101, ResRelationGetListToClientMessage, ResRelationGetListToClientHandler);
            this.register(119102, ResRelationAddOrChangeToClientMessage, ResRelationAddOrChangeToClientHandler);
            this.register(119103, ResRelationDeleteToClientMessage, ResRelationDeleteToClientHandler);
            this.register(121101, ResGuildCreateToClientMessage, ResGuildCreateToClientHandler);
            this.register(121102, ResGuildAutoArgeeAddGuildToClientMessage, ResGuildAutoArgeeAddGuildToClientHandler);
            this.register(121103, ResGuildGetGuildListToClientMessage, ResGuildGetGuildListToClientHandler);
            this.register(121104, ResGuildApplyAddDoingToClientMessage, ResGuildApplyAddDoingToClientHandler);
            this.register(121105, ResGuildInviteAddDoingToClientMessage, ResGuildInviteAddDoingToClientHandler);
            this.register(121106, ResGuildGetMemberListToClientMessage, ResGuildGetMemberListToClientHandler);
            this.register(121107, ResGuildAddMemberToClientMessage, ResGuildAddMemberToClientHandler);
            this.register(121108, ResGuildQuitToClientMessage, ResGuildQuitToClientHandler);
            this.register(121109, ResGuildChangeNickNameToClientMessage, ResGuildChangeNickNameToClientHandler);
            this.register(121110, ResGuildChangePowerLevelToClientMessage, ResGuildChangePowerLevelToClientHandler);
            this.register(121111, ResGuildDeleteMemberToClientMessage, ResGuildDeleteMemberToClientHandler);
            this.register(121112, ResGuildAutoGuildArgeeAddToClientMessage, ResGuildAutoGuildArgeeAddToClientHandler);
            this.register(121113, ResGuildChangeBulletinToClientMessage, ResGuildChangeBulletinToClientHandler);
            this.register(121114, ResGuildSubmitItemToClientMessage, ResGuildSubmitItemToClientHandler);
            this.register(121115, ResGuildChangeBannerIconToClientMessage, ResGuildChangeBannerIconToClientHandler);
            this.register(121116, ResGuildChangeBannerNameToClientMessage, ResGuildChangeBannerNameToClientHandler);
            this.register(121117, ResGuildBannerLevelUpToClientMessage, ResGuildBannerLevelUpToClientHandler);
            this.register(121118, ResGuildAddDiplomaticToClientMessage, ResGuildAddDiplomaticToClientHandler);
            this.register(121119, ResGuildDeleteDiplomaticToClientMessage, ResGuildDeleteDiplomaticToClientHandler);
            this.register(121120, ResGuildDeleteGuildToClientMessage, ResGuildDeleteGuildToClientHandler);
            this.register(121121, ResGuildGetEventListToClientMessage, ResGuildGetEventListToClientHandler);
            this.register(121501, ResGuildAloneGuildInfoToClientMessage, ResGuildAloneGuildInfoToClientHandler);
            this.register(121502, ResGuildAloneMemberInfoToClientMessage, ResGuildAloneMemberInfoToClientHandler);
            this.register(100101, ResCharacterInfosMessage, ResCharacterInfosHandler);
            this.register(100102, ResLoginSuccessMessage, ResLoginSuccessHandler);
            this.register(100103, ResSubstituteMessage, ResSubstituteHandler);
            this.register(101101, ResRoundPlayerMessage, ResRoundPlayerHandler);
            this.register(101102, ResRoundMonsterMessage, ResRoundMonsterHandler);
            this.register(101103, ResRoundGoodsMessage, ResRoundGoodsHandler);
            this.register(101104, ResRoundPetMessage, ResRoundPetHandler);
            this.register(101105, ResRoundPlayerDisappearMessage, ResRoundPlayerDisappearHandler);
            this.register(101106, ResRoundMonsterDisappearMessage, ResRoundMonsterDisappearHandler);
            this.register(101107, ResRoundGoodsDisappearMessage, ResRoundGoodsDisappearHandler);
            this.register(101108, ResRoundPetDisappearMessage, ResRoundPetDisappearHandler);
            this.register(101109, ResSetPositionMessage, ResSetPositionHandler);
            this.register(101110, ResRunPositionsMessage, ResRunPositionsHandler);
            this.register(101111, ResMonsterRunPositionsMessage, ResMonsterRunPositionsHandler);
            this.register(101112, ResPlayerJumpPositionsMessage, ResPlayerJumpPositionsHandler);
            this.register(101113, ResStartBlockMessage, ResStartBlockHandler);
            this.register(101114, ResStopBlockMessage, ResStopBlockHandler);
            this.register(101115, ResMonsterStopMessage, ResMonsterStopHandler);
            this.register(101116, ResPlayerStopMessage, ResPlayerStopHandler);
            this.register(101117, ResChangeMapMessage, ResChangeMapHandler);
            this.register(101118, ResWeaponChangeMessage, ResWeaponChangeHandler);
            this.register(101119, ResArmorChangeMessage, ResArmorChangeHandler);
            this.register(101120, ResEnterMapMessage, ResEnterMapHandler);
            this.register(101701, ResSynPlayerPositionMessage, ResSynPlayerPositionHandler);
            this.register(114101, ResMonsterHpChangeMessage, ResMonsterHpChangeHandler);
            this.register(114102, ResMonsterMpChangeMessage, ResMonsterMpChangeHandler);
            this.register(114103, ResMonsterSpChangeMessage, ResMonsterSpChangeHandler);
            this.register(114104, ResMonsterMaxHpChangeMessage, ResMonsterMaxHpChangeHandler);
            this.register(114105, ResMonsterMaxMpChangeMessage, ResMonsterMaxMpChangeHandler);
            this.register(114106, ResMonsterMaxSpChangeMessage, ResMonsterMaxSpChangeHandler);
            this.register(114107, ResMonsterSpeedChangeMessage, ResMonsterSpeedChangeHandler);
            this.register(114108, ResMonsterDieMessage, ResMonsterDieHandler);
            this.register(114109, ResMonsterReviveMessage, ResMonsterReviveHandler);
            this.register(103101, ResPlayerHpChangeMessage, ResPlayerHpChangeHandler);
            this.register(103102, ResReviveSuccessMessage, ResReviveSuccessHandler);
            this.register(103103, ResPlayerExpChangeMessage, ResPlayerExpChangeHandler);
            this.register(510001, ResPlayerChangeJobMessage, ResPlayerJobChangeHandler);
            this.register(103104, ResPlayerLevelUpMessage, ResPlayerLevelUpHandler);
            this.register(103105, ResPlayerMpChangeMessage, ResPlayerMpChangeHandler);
            this.register(103106, ResPlayerSpChangeMessage, ResPlayerSpChangeHandler);
            this.register(103107, ResMyPlayerInfoMessage, ResMyPlayerInfoHandler);
            this.register(103108, ResOtherPlayerInfoMessage, ResOtherPlayerInfoHandler);
            this.register(103109, ResPlayerMaxHpChangeMessage, ResPlayerMaxHpChangeHandler);
            this.register(103110, ResPlayerMaxMpChangeMessage, ResPlayerMaxMpChangeHandler);
            this.register(103111, ResPlayerMaxSpChangeMessage, ResPlayerMaxSpChangeHandler);
            this.register(103112, ResPlayerSpeedChangeMessage, ResPlayerSpeedChangeHandler);
            this.register(103113, ResPlayerZhenqiChangeMessage, ResPlayerZhenqiChangeHandler);
            this.register(103114, ResPlayerBattleExpChangeMessage, ResPlayerBattleExpChangeHandler);
            this.register(103115, ResPlayerDieMessage, ResPlayerDieHandler);
            this.register(103118, ResChangePKStateMessage, ResChangePKStateHandler);
            this.register(121130, ResPlayerGuildChangeMessage, ResChangeGuildHandler);
            this.register(103119, ResPlayerAttributeChangeMessage, ResPlayerAttributeChangeHandler);
            this.register(103120, ResPlayerStateChangeMessage, ResPlayerStateChangeHandler);
            this.register(109101, PersonalPromptMessage, PersonalPromptHandler);
            this.register(109102, PersonalNoticeMessage, PersonalNoticeHandler);
            this.register(109103, GMNoticeMessage, GMNoticeHandler);
            this.register(109104, WorldNoticeMessage, WorldNoticeHandler);
            this.register(109105, PersonalPromptWorldMessage, PersonalPromptWorldHandler);
            this.register(109106, PersonalNoticeWorldMessage, PersonalNoticeWorldHandler);
            this.register(109107, GMNoticeWorldMessage, GMNoticeWorldHandler);
            this.register(109108, WorldNoticeWorldMessage, WorldNoticeWorldHandler);
            this.register(105101, ResNotSaleMessage, ResNotSaleHandler);
            this.register(105102, ResSaleSuccessMessage, ResSaleSuccessHandler);
            this.register(105103, ResRebuySuccessMessage, ResRebuySuccessHandler);
            this.register(105104, ResRebuyItemInfosMessage, ResRebuyItemInfosHandler);
            this.register(108101, ShortCutInfosMessage, ShortCutInfosHandler);
            this.register(108102, ShortCutAddMessage, ShortCutAddHandler);
            this.register(108103, ShortCutRemoveMessage, ShortCutRemoveHandler);
            this.register(107101, SkillInfosMessage, SkillInfosHandler);
            this.register(107102, SkillAddMessage, SkillAddHandler);
            this.register(107103, SkillStartLevelUpMessage, SkillStartLevelUpHandler);
            this.register(107104, SkillRemoveMessage, SkillRemoveHandler);
            this.register(107105, SkillLingWuResultMessage, SkillLingWuResultHandler);
            this.register(107106, NowLeranSkillMessage, NowLeranSkillHandler);
            this.register(123101, ResStallsOpenUpMessage, ResStallsOpenUpHandler);
            this.register(123102, ResStallsPlayerIdLookMessage, ResStallsPlayerIdLookHandler);
            this.register(123103, ResStallsSortMessage, ResStallsSortHandler);
            this.register(123104, ResStallsBuyMessage, ResStallsBuyHandler);
            this.register(123105, ResStallsProductWasAddedMessage, ResStallsProductWasAddedHandler);
            this.register(123106, ResStallsAdjustPricesMessage, ResStallsAdjustPricesHandler);
            this.register(123107, ResStallsOffShelfMessage, ResStallsOffShelfHandler);
            this.register(123108, ResStallsSearchMessage, ResStallsSearchHandler);
            this.register(123109, ResStallsLooklogMessage, ResAuctionLooklogHandler);
            this.register(123110, ResChangeStallsNameMessage, ResChangeStallsNameHandler);
            this.register(112100, ResStoreItemInfosMessage, ResStoreItemInfosHandler);
            this.register(112101, ResStoreItemAddMessage, ResStoreItemAddHandler);
            this.register(112102, ResStoreItemChangeMessage, ResStoreItemChangeHandler);
            this.register(112103, ResStoreItemRemoveMessage, ResStoreItemRemoveHandler);
            this.register(112105, ResStoreCellTimeMessage, ResStoreCellTimeHandler);
            this.register(112106, ResStoreOpenCellResultMessage, ResStoreOpenCellResultHandler);
            this.register(120101, ResTaskListMessage, ResTaskListHandler);
            this.register(120102, ResTaskFinshMessage, ResTaskFinshHandler);
            this.register(120103, ResRewardsAbleActMessage, ResRewardsAbleActHandler);
            this.register(120104, ResMainTaskChangeMessage, ResMainTaskChangeHandler);
            this.register(120105, ResDailyTaskChangeMessage, ResDailyTaskChangeHandler);
            this.register(120106, ResConquerTaskChangeMessage, ResConquerTaskChangeHandler);
            this.register(120107, ResConquerTaskAnnexMessage, ResConquerTaskAnnexHandler);
            this.register(120108, ResTaskReceiveMessage, ResTaskReceiveHandler);
            this.register(118101, ResTeamClientRefreshMessage, ResTeamClientRefreshHandler);
            this.register(118102, ResApplyClientMessage, ResApplyClientHandler);
            this.register(118103, ResInviteClientMessage, ResInviteClientHandler);
            this.register(118104, ResAppointClientMessage, ResAppointClientHandler);
            this.register(118105, ResTeamExteriorClientMessage, ResTeamExteriorClientHandler);
            this.register(118106, ResAutoTeaminvitedClientMessage, ResAutoTeaminvitedClientHandler);
            this.register(118107, ResAutoIntoTeamApplyClientMessage, ResAutoIntoTeamApplyClientHandler);
            this.register(118108, ResMapSearchTeamInfoClientMessage, ResMapSearchTeamInfoClientHandler);
            this.register(118109, ResMapSearchPlayerInfoClientMessage, ResMapSearchPlayerInfoClientHandler);
            this.register(122111, ResTransactionsErrorMessage, ResTransactionsErrorHandler);
            this.register(122112, ResTmpYuanbaoLogMessage, ResTmpYuanbaoLogHandler);
            this.register(123111, ResStallsErrorMessage, ResStallsErrorHandler);
            this.register(103121, ResPlayerNonageStateMessage, ResPlayerNonageStateHandler);
            this.register(103122, ResPlayerNonageTimeMessage, ResPlayerNonageTimeHandler);
            this.register(109109, NonagePromptMessage, NonagePromptHandler);
            this.register(100104, ResCreateFailedMessage, ResCreateFailedHandler);
            this.register(100105, ResDeleteSuccessMessage, ResDeleteSuccessHandler);
            this.register(119104, ResRelationIconTipToClientMessage, ResRelationIconTipToClientHandler);
            this.register(103123, ResPlayerNonageRegisterMessage, ResPlayerNonageRegisterHandler);
            this.register(114110, ResMonsterSayMessage, ResMonsterSayHandler);
            this.register(118110, ResMapSearchMemberNameClientMessage, ResMapSearchMemberNameClientHandler);
            this.register(118111, ResGenericSearchToClientMessage, ResGenericSearchToClientHandler);
            this.register(115102, ResLongYuanActivationMessage, ResLongYuanActivationHandler);
            this.register(115103, ResLongYuanPosTipsMessage, ResLongYuanPosTipsHandler);
            this.register(115104, ResLongYuanStarMapTipsMessage, ResLongYuanStarMapTipsHandler);
            this.register(115105, ResLongYuanTimerMessage, ResLongYuanTimerHandler);
            this.register(118112, ResTeammateMoveToClientMessage, ResTeammateMoveToClientHandler);
            this.register(115101, ResLongYuanOpenMessage, ResLongYuanOpenHandler);
            this.register(118113, ResTeamSetToClientMessage, ResTeamSetToClientHandler);
            this.register(115106, ResShowEffectToClientMessage, ResShowEffectToClientHandler);
            this.register(121390, ResGuildAloneGuildInfoToClientMessage, ResGuildAloneGuildInfoToClientHandler);
            this.register(121391, ResGuildAloneMemberInfoToClientMessage, ResGuildAloneMemberInfoToClientHandler);
            this.register(101702, ResSynMonsterPositionMessage, ResSynMonsterPositionHandler);
            this.register(119250, ResRelationConfigToClientMessage, ResRelationConfigToClientHandler);
            this.register(125101, ResMenuStatusMessage, ResMenuStatusHandler);
            this.register(123112, ResStallsExpMessage, ResStallsExpHandler);
            this.register(101121, ResPetStopMessage, ResPetStopHandler);
            this.register(101122, ResPetRunPositionsMessage, ResPetRunPositionsHandler);
            this.register(101123, ResPlayerRunEndMessage, ResPlayerRunEndHandler);
            this.register(107107, SkillChangeMessage, SkillChangeHandler);
            this.register(101703, ResMapBlocksMessage, ResMapBlocksHandler);
            this.register(100106, ResLoginFailedMessage, ResLoginFailedHandler);
            this.register(126101, ResHorseInfoMessage, ResHorseInfoHandler);
            this.register(126102, ResRidingCountdownMessage, ResRidingCountdownHandler);
            this.register(126103, ResRidingStateMessage, ResRidingStateHandler);
            this.register(126104, ReshorseStageUpPanelMessage, ReshorseStageUpPanelHandler);
            this.register(126105, ReshorseStageUpResultMessage, ReshorseStageUpResultHandler);
            this.register(126106, ReshorseLuckyRodMessage, ReshorseLuckyRodHandler);
            this.register(126107, ReshorseLuckyPenteMessage, ReshorseLuckyPenteHandler);
            this.register(100107, ResQuitMessage, ResQuitHandler);
            this.register(121392, ResGuildDeleteInfoRoundToClientMessage, ResGuildDeleteInfoRoundToClientHandler);
            this.register(126108, ReshorseReceiveMessage, ReshorseReceiveHandler);
            this.register(126109, ReshorseReceiveTimerMessage, ReshorseReceiveTimerHandler);
            this.register(126110, ReshorseErrInfoMessage, ReshorseErrInfoHandler);
            this.register(126111, ReshorseCDTimeMessage, ReshorseCDTimeHandler);
            this.register(126112, ResOthersHorseInfoMessage, ResOthersHorseInfoHandler);
            this.register(100108, ResHeartMessage, ResHeartHandler);
            this.register(120109, ResConquerTaskListUpdateMessage, ResConquerTaskListUpdateHandler);
            this.register(120110, ResTargetMonsterChangeMessage, ResTargetMonsterChangeHandler);
            this.register(121122, ResGuildGetGuildShortInfoListToClientMessage, ResGuildGetGuildShortInfoListToClientHandler);
            this.register(127201, ResFightPowerToClientMessage, ResFightPowerToClientHandler);
            this.register(126113, ResOpenSkillUpPanelMessage, ResOpenSkillUpPanelHandler);
            this.register(128101, ResZonePanelSelectMessage, ResZonePanelSelectHandler);
            this.register(128102, ResZoneTimerMessage, ResZoneTimerHandler);
            this.register(128103, ResZonePassShowMessage, ResZonePassShowHandler);
            this.register(128104, ResZoneSelectAwardMessage, ResZoneSelectAwardHandler);
            this.register(103124, ResPlayerAvatarMessage, ResPlayerAvatarHandler);
            this.register(129101, ResSendGiftItemsToClientMessage, ResSendGiftItemsToClientHandler);
            this.register(126114, ResSkillInfoMessage, ResSkillInfoHandler);
            this.register(130101, ResStrengItemToClientMessage, ResStrengItemToClientHandler);
            this.register(103894, ResComposeItemToClientMessage, ResComposeItemToClientHandler);
            this.register(103895, ResEquipPetMessage, WearCutePetItemUpdateHandler);
            this.register(130102, ResStageUpItemToClientMessage, ResStageUpItemToClientHandler);
            this.register(130103, ResErrorInfoToClientMessage, ResErrorInfoToClientHandler);
            this.register(102104, ResEffectBroadcastMessage, ResEffectBroadcastHandler);
            this.register(130104, ResStrengthenStateMessage, ResStrengthenStateHandler);
            this.register(131101, ResPlugSetInfoMessage, ResPlugSetInfoHandler);
            this.register(103125, ResPlayerCheckOnlineMessage, ResPlayerCheckOnlineHandler);
            this.register(103126, ResGetPlayerAppearanceInfMessage, ResGetPlayerAppearanceInfHandler);
            this.register(101124, ResSendLinesMessage, ResSendLinesHandler);
            this.register(105105, ResShopItemListMessage, ResShopItemListHandler);
            this.register(132101, ResOpenGemPanelMessage, ResOpenGemPanelHandler);
            this.register(132102, ResGemIntoMessage, ResGemIntoHandler);
            this.register(132103, ResGemActivationORUpMessage, ResGemActivationORUpHandler);
            this.register(132104, ResGemExtraExpMessage, ResGemExtraExpHandler);
            this.register(132105, ResGemErrorInfoMessage, ResGemErrorInfoHandler);
            this.register(100109, ResDelPlayerStatusToClientMessage, ResDelPlayerStatusToClientHandler);
            this.register(120302, ResTargetMonsterInfoMessage, ResTargetMonsterInfoHandler);
            this.register(103127, ResChangePlayerNameToClientMessage, ResChangePlayerNameToClientHandler);
            this.register(100110, ResCreateUserMessage, ResCreateUserHandler);
            this.register(103128, ResPlayerNameInfoToClientMessage, ResPlayerNameInfoToClientHandler);
            this.register(103129, ResChangePlayerUserToClientMessage, ResChangePlayerUserToClientHandler);
            this.register(111103, ChatResponseWCMessage, ChatResponseWCHandler);
            this.register(109110, AddToFavoriteMessage, AddToFavoriteHandler);
            this.register(101125, ResRoundObjectsMessage, ResRoundObjectsHandler);
            this.register(105106, ResBuyItemResultMessage, ResBuyItemResultHandler);
            this.register(300101, ResCloseServerMessage, ResCloseServerHandler);
            this.register(133101, ResGetAllFruitInfoToClientMessage, ResGetAllFruitInfoToClientHandler);
            this.register(133102, ResGetSingleFruitInfoToClientMessage, ResGetSingleFruitInfoToClientHandler);
            this.register(133103, ResOpenGuildFruitToClientMessage, ResOpenGuildFruitToClientHandler);
            this.register(133104, ResShowToRewardListToClientMessage, ResShowToRewardListToClientHandler);
            this.register(133105, ResShowGuildMatureClientMessage, ResShowGuildMatureClientHandler);
            this.register(101126, ResChangeMapFailedMessage, ResChangeMapFailedHandler);
            this.register(101127, ResChangeDirectMessage, ResChangeDirectHandler);
            this.register(104212, ResTakeUpSuccessMessage, ResTakeUpSuccessHandler);
            this.register(136101, ResDazuoStateChangeMessage, ResDazuoStateChangeHandler);
            this.register(136102, ResDazuoStateBroadCastMessage, ResDazuoStateBroadCastHandler);
            this.register(136103, ResDazuoEruptMessage, ResDazuoEruptHandler);
            this.register(136104, ResShuangXiuApplyMessage, ResShuangXiuApplyHandler);
            this.register(113105, ResChangeBuffMessage, ResChangeBuffHandler);
            this.register(202101, ResVersionUpdateToClientMessage, ResVersionUpdateToClientHandler);
            this.register(202102, ResVersionResInfoMessage, ResVersionResInfoHandler);
            this.register(138101, ResActivitiesInfoMessage, ResActivitiesInfoHandler);
            this.register(133106, ResRipeningDecYBToClientMessage, ResRipeningDecYBToClientHandler);
            this.register(101128, ResChangePositionMessage, ResChangePositionHandler);
            this.register(137151, ResCardToClientMessage, ResCardToClientHandler);
            this.register(139101, ResYBCardToClientMessage, ResYBCardToClientHandler);
            this.register(133107, ResGuildFruitLogToClientMessage, ResGuildFruitLogToClientHandler);
            this.register(133108, ResFruitErrorToClientMessage, ResFruitErrorToClientHandler);
            this.register(101129, ResRoundNpcMessage, ResRoundNpcHandler);
            this.register(101130, ResRoundNpcDisappearMessage, ResRoundNpcDisappearHandler);
            this.register(101131, ResRoundEffectMessage, ResRoundEffectHandler);
            this.register(101132, ResRoundEffectDisappearMessage, ResRoundEffectDisappearHandler);
            this.register(128105, ResZoneClearanceMessage, ResZoneClearanceHandler);
            this.register(128106, ResAllRaidZoneInfoMessage, ResAllRaidZoneInfoHandler);
            this.register(128107, ResAutoRaidInfoMessage, ResAutoRaidInfoHandler);
            this.register(103130, ResScriptCommonPlayerToClientMessage, ResScriptCommonPlayerToClientHandler);
            this.register(128108, ResZoneNoticeRewardMessage, ResZoneNoticeRewardHandler);
            this.register(114111, ResMonsterDoubleNoticeMessage, ResMonsterDoubleNoticeHandler);
            this.register(128109, ResZoneKillProgressRateMessage, ResZoneKillProgressRateHandler);
            this.register(141101, ResMonsterBatterToClientMessage, ResMonsterBatterToClientHandler);
            this.register(141102, ResMomentKillToClientMessage, ResMomentKillToClientHandler);
            this.register(124101, ResMailQueryListToClientMessage, ResMailQueryListToClientHandler);
            this.register(124102, ResMailQueryDetailToClientMessage, ResMailQueryDetailToClientHandler);
            this.register(124103, ResMailGetItemToClientMessage, ResMailGetItemToClientHandler);
            this.register(124104, ResMailSendNewMailToClientMessage, ResMailSendNewMailToClientHandler);
            this.register(124106, ResMailQueryUserToClientMessage, ResMailQueryUserToClientHandler);
            this.register(124107, ResMailReturnToClientMessage, ResMailReturnToClientHandler);
            this.register(124110, ResMailGetNewMailToClientMessage, ResMailGetNewMailToClientHandler);
            this.register(140101, ResNpcServicesMessage, ResNpcServicesHandler);
            this.register(129102, ResSendGiftInfoToClientMessage, ResSendGiftInfoToClientHandler);
            this.register(142101, ResGetTopListToClientMessage, ResGetTopListToClientHandler);
            this.register(142102, ResWorShipToClientMessage, ResWorShipToClientHandler);
            this.register(140102, ResStartGatherMessage, ResStartGatherHandler);
            this.register(140103, ResStopGatherMessage, ResStopGatherHandler);
            this.register(140104, ResNpcActionMessage, ResNpcActionHandler);
            this.register(120111, ResTreasureHuntTaskChangeMessage, ResTreasureHuntTaskChangeHandler);
            this.register(143101, ResEpalaceWalkToClientMessage, ResEpalaceWalkToClientHandler);
            this.register(143102, ResEpalaceDiceToClientMessage, ResEpalaceDiceToClientHandler);
            this.register(143103, ResEpalaceOpenToGameMessage, ResEpalaceOpenToGameHandler);
            this.register(143104, ResEpalaceErrorToGameMessage, ResEpalaceErrorToGameHandler);
            this.register(120112, ResGiveUpTaskMessage, ResGiveUpTaskHandler);
            this.register(143105, ResEpalaceDialToClientMessage, ResEpalaceDialToClientHandler);
            this.register(103131, ResScriptCommonPlayerWorldToClientMessage, ResScriptCommonPlayerWorldToClientHandler);
            this.register(143106, ResEpalaceRewardInfoToClientMessage, ResEpalaceRewardInfoToClientHandler);
            this.register(102105, ResFightFailedBroadcastMessage, ResFightFailedBroadcastHandler);
            this.register(120113, ResTargetMonsterMessage, ResTargetMonsterHandler);
            this.register(142150, ResGetTopTitleToClientMessage, ResGetTopTitleToClientHandler);
            this.register(128110, ResZoneLifeTimeMessage, ResZoneLifeTimeHandler);
            this.register(114112, ResQueryBossListResultMessage, ResQueryBossListResultHandler);
            this.register(144101, ResOpenChallengeToClientMessage, ResOpenChallengeToClientHandler);
            this.register(110101, ResPetListMessage, ResPetListHandler);
            this.register(110102, ResPetAddMessage, ResPetAddHandler);
            this.register(110103, ResPetChangeMessage, ResPetChangeHandler);
            this.register(110104, ResPetHeTiResultMessage, ResPetHeTiResultHandler);
            this.register(110105, ResPetAttributeChangeMessage, ResPetAttributeChangeHandler);
            this.register(110106, ResPetDieMessage, ResPetDieHandler);
            this.register(110107, ResPetReviveMessage, ResPetReviveHandler);
            this.register(110108, ResPetShowMessage, ResPetShowHandler);
            this.register(110109, ResPetHidenMessage, ResPetHidenHandler);
            this.register(110110, ResPetSkillChangeMessage, ResPetSkillChangeHandler);
            this.register(110111, ResPetDieBroadcastMessage, ResPetDieBroadcastHandler);
            this.register(110112, ResPetHTCDClearResultMessage, ResPetHTCDClearResultHandler);
            this.register(144102, ResRewardChallengeToClientMessage, ResRewardChallengeToClientHandler);
            this.register(145101, ResChangeFloorMessage, ResChangeFloorHandler);
            this.register(145102, ResRewardMessage, ResRewardHandler);
            this.register(138102, ResReceiveLiJinGiftResultMessage, ResReceiveLiJinGiftResultHandler);
            this.register(128111, ResZoneBossAppearMessage, ResZoneBossAppearHandler);
            this.register(128112, ResZoneTimeRecordNoticeMessage, ResZoneTimeRecordNoticeHandler);
            this.register(101133, ResPetJumpPositionsMessage, ResPetJumpPositionsHandler);
            this.register(146101, ReqCountrySiegeSelectToClientMessage, ReqCountrySiegeSelectToClientHandler);
            this.register(146102, ResCountrySiegeUpYuxiToClientMessage, ResCountrySiegeUpYuxiToClientHandler);
            this.register(146103, ResCountrySiegeHomingYuxiToClientMessage, ResCountrySiegeHomingYuxiToClientHandler);
            this.register(146104, ResCountrySiegeYuXiImmediateToClientMessage, ResCountrySiegeYuXiImmediateToClientHandler);
            this.register(146105, ResCountryStructureInfoToClientMessage, ResCountryStructureInfoToClientHandler);
            this.register(146106, ResCountryArtilleryLocusToClientMessage, ResCountryArtilleryLocusToClientHandler);
            this.register(300102, ResDiscardMsgMessage, ResDiscardMsgHandler);
            this.register(142151, ResTopListChestInfoToClientMessage, ResTopListChestInfoToClientHandler);
            this.register(146107, ResCountrySiegeWarStateToClientMessage, ResCountrySiegeWarStateToClientHandler);
            this.register(146108, ResKingCityChestPanelShowToClientMessage, ResKingCityChestPanelShowToClientHandler);
            this.register(146109, ResKingCityChestSelectToClientMessage, ResKingCityChestSelectToClientHandler);
            this.register(146110, ResKingCityTimeRewardToClientMessage, ResKingCityTimeRewardToClientHandler);
            this.register(147101, ResPlayerVIPInfoMessage, ResPlayerVIPInfoHandler);
            this.register(147102, ResUseVIPCardResultMessage, ResUseVIPCardResultHandler);
            this.register(101134, ResPetTranMoveMessage, ResPetTranMoveHandler);
            this.register(110113, ResPetChatMessage, ResPetChatHandler);
            this.register(147103, ResVIPAnnounceMessage, ResVIPAnnounceHandler);
            this.register(147104, ResVIPExpiredMessage, ResVIPExpiredHandler);
            this.register(110114, ResPetTargetMessage, ResPetTargetHandler);
            this.register(146111, ResKingCityYuXiCoordinateToClientMessage, ResKingCityYuXiCoordinateToClientHandler);
            this.register(146112, ResCountryWarCarDamageToClientMessage, ResCountryWarCarDamageToClientHandler);
            this.register(146113, ResAwardInfoToClientMessage, ResCountryRewardNumToClientHandler);
            this.register(138110, ResActivitiesInfoWorldMessage, ResActivitiesInfoWorldHandler);
            this.register(128113, ResZoneSurplusSumMessage, ResZoneSurplusSumHandler);
            this.register(109111, PersonalNoticeActivityMessage, PersonalNoticeActivityHandler);
            this.register(133109, ResFruitTheftNumToClientMessage, ResFruitTheftNumToClientHandler);
            this.register(137251, ResCardPhoneToClientMessage, ResCardPhoneToClientHandler);
            this.register(114113, ResRefreshBOSSSurplusTimeMessage, ResRefreshBOSSSurplusTimeHandler);
            this.register(200101, GmLevelMessage, GmLevelHandler);
            this.register(148101, ResScriptPaneleMessage, ResScriptPaneleHandler);
            this.register(128114, ResZoneContinuousRaidsMessage, ResZoneContinuousRaidsHandler);
            this.register(128115, ResZoneContinuousRaidsEndMessage, ResZoneContinuousRaidsEndHandler);
            this.register(132106, ResGemStrengthenPanelMessage, ResGemStrengthenPanelHandler);
            this.register(128116, ResZoneTeamShowToClientMessage, ResZoneTeamShowToClientHandler);
            this.register(128117, ResZoneTeamNoticeToClientMessage, ResZoneTeamNoticeToClientHandler);
            this.register(128118, ResZoneTeamNoticeSelectToClientMessage, ResZoneTeamNoticeSelectToClientHandler);
            this.register(104214, ResGetItemReasonsMessage, ResGetItemReasonsHandler);
            this.register(149101, ResOpenGuildFlagToClientMessage, ResOpenGuildFlagToClientHandler);
            this.register(150203, ResRetreatInfoMessage, ResRetreatInfoHandler);
            this.register(149102, ResGuildFlagStatusToClientMessage, ResGuildFlagStatusToClientHandler);
            this.register(138103, ResCallEveryDay0ClockMessage, ResCallEveryDay0ClockHandler);
            this.register(117101, ResRankinfoToClientMessage, ResRankinfoToClientHandler);
            this.register(117102, ResRankExpToClientMessage, ResRankExpToClientHandler);
            this.register(117103, ResRankUPToClientMessage, ResRankUPToClientHandler);
            this.register(151101, ResArrowInfoMessage, ResArrowInfoHandler);
            this.register(151102, ResStarInfoMessage, ResStarInfoHandler);
            this.register(151103, ResBowInfoMessage, ResBowInfoHandler);
            this.register(151104, ResFightSpiritInfoMessage, ResFightSpiritInfoHandler);
            this.register(120114, ResRankTaskListMessage, ResRankTaskListHandler);
            this.register(120115, ResRankTaskChangeMessage, ResRankTaskChangeHandler);
            this.register(128119, ResZoneTeamOpenBullToClientMessage, ResZoneTeamOpenBullToClientHandler);
            this.register(120116, ResRankTaskFinshMessage, ResRankTaskFinshHandler);
            this.register(152101, ResSignWageInfoMessage, ResSignWageInfoHandler);
            this.register(152102, ResSignWagetoWageInfoMessage, ResSignWagetoWageInfoHandler);
            this.register(152103, ResWageERNIEinofMessage, ResWageERNIEinofHandler);
            this.register(152104, RessignnumToClientMessage, RessignnumToClientHandler);
            this.register(151105, ResFightSpiritGetNumMessage, ResFightSpiritGetNumHandler);
            this.register(104112, ResNotEnoughGoldChangeMessage, ResNotEnoughGoldChangeHandler);
            this.register(151106, ResRoundArrowExteriorMessage, ResRoundArrowExteriorHandler);
            this.register(101135, ResJumpSetPositionMessage, ResJumpSetPositionHandler);
            this.register(148102, ResShowPaneleInfoToClientMessage, ResShowPaneleInfoToClientHandler);
            this.register(148103, ResPanelStatusInfoToClientMessage, ResPanelStatusInfoToClientHandler);
            this.register(120117, ResRankTaskQuickFinshAllMessage, ResRankTaskQuickFinshAllHandler);
            this.register(133110, ResContinuousRipeningToClientMessage, ResContinuousRipeningToClientHandler);
            this.register(103132, ResVipPlayerChangeMapToClientMessage, ResVipPlayerChangeMapToClientHandler);
            this.register(153101, ResCollectInfoMessage, ResCollectInfoHandler);
            this.register(154101, ResMeltingItemToClientMessage, ResMeltingItemToClientHandler);
            this.register(103133, ResAutoStartStateMessage, ResAutoStartStateHandler);
            this.register(155101, ResHorseWeaponInfoMessage, ResHorseWeaponInfoHandler);
            this.register(155102, ResWearHorseWeaponStateMessage, ResWearHorseWeaponStateHandler);
            this.register(155103, ResHorseWeaponStageUpPanelMessage, ResHorseWeaponStageUpPanelHandler);
            this.register(155104, ResHorseWeaponStageUpResultMessage, ResHorseWeaponStageUpResultHandler);
            this.register(155105, ResOthersHorseWeaponInfoMessage, ResOthersHorseWeaponInfoHandler);
            this.register(156101, ResChestBoxInfoToClientMessage, ResChestBoxInfoToClientHandler);
            this.register(156102, ResChestBoxChooseInfoToClientMessage, ResChestBoxChooseInfoToClientHandler);
            this.register(156103, ResChestBoxNewGridInfoToClientMessage, ResChestBoxNewGridInfoToClientHandler);
            this.register(156104, ResChestBoxAutoSetToClientMessage, ResChestBoxAutoSetToClientHandler);
            this.register(155106, ResHorseWeaponErrorMessage, ResHorseWeaponErrorHandler);
            this.register(129103, ResPlatformGiftListMessage, ResPlatformGiftListHandler);
            this.register(129104, ResGetPlatformGiftMessage, ResGetPlatformGiftHandler);
            this.register(157101, ResBiWuInfoToClientMessage, ResBiWuInfoToClientHandler);
            this.register(157102, ResBiWuDaoAreadoubleToClientMessage, ResBiWuDaoAreadoubleToClientHandler);
            this.register(157103, ResBiWuDaoTotalGainToClientMessage, ResBiWuDaoTotalGainToClientHandler);
            this.register(157104, ResBiWuDaoGuildnameToClientMessage, ResBiWuDaoGuildnameToClientHandler);
            this.register(157105, ResBiWuDaoFlagCoolDownToClientMessage, ResBiWuDaoFlagCoolDownToClientHandler);
            this.register(157106, ResBiWuDaoSurplusTimeToClientMessage, ResBiWuDaoSurplusTimeToClientHandler);
            this.register(120118, ResTaskGoldAddNumMessage, ResTaskGoldAddNumHandler);
            this.register(157107, ResBiWuDaoStatusShowToClientMessage, ResBiWuDaoStatusShowToClientHandler);
            this.register(128120, ResZoneApplyDataInfoToClientMessage, ResZoneApplyDataInfoToClientHandler);
            this.register(129105, ResShuffleRaffleMessage, ResShuffleRaffleHandler);
            this.register(100111, ResRolesCreateReportToClientMessage, ResRolesCreateReportToClientHandler);
            this.register(103134, ResPlayerPrisonStateMessage, ResPlayerPrisonStateHandler);
            this.register(203101, ResChangeServerMessage, ResChangeServerHandler);
            this.register(204101, ResLoginFailedForPublicMessage, ResLoginFailedForPublicHandler);
            this.register(204102, ResQuitForPublicMessage, ResQuitForPublicHandler);
            this.register(158101, ResRealmInfoToClientMessage, ResRealmInfoToClientHandler);
            this.register(158102, ResBreakthroughToClientMessage, ResBreakthroughToClientHandler);
            this.register(158103, ResIntensifyToClientMessage, ResIntensifyToClientHandler);
            this.register(159101, ResWineInfoMessage, ResWineInfoHandler);
            this.register(159102, ResWineUpdateMessage, ResWineUpdateHandler);
            this.register(146114, ResCountryTopInfoToClientMessage, ResCountryTopInfoToClientHandler);
            this.register(546114, ResCountryOverTopInfoToClientMessage, ResCountryOverTopInfoToClientHandler);
            this.register(158104, ResRealmErrToClientMessage, ResRealmErrToClientHandler);
            this.register(103135, ResJumpMaxSpeedMessage, ResJumpMaxSpeedHandler);
            this.register(160100, ResBagSynMessage, ResBagSynHandler);
            this.register(160101, ResBagItemAddMessage, ResBagItemAddHandler);
            this.register(160102, ResBagItemUpdateMessage, ResBagItemUpdateHandler);
            this.register(160103, ResBagItemRemoveMessage, ResBagItemRemoveHandler);
            this.register(162101, ResHiddenWeaponInfoMessage, ResHiddenWeaponInfoHandler);
            this.register(162102, ResWearHiddenWeaponStateMessage, ResWearHiddenWeaponStateHandler);
            this.register(162103, ResHiddenWeaponStageUpPanelMessage, ResHiddenWeaponStageUpPanelHandler);
            this.register(162104, ResHiddenWeaponStageUpResultMessage, ResHiddenWeaponStageUpResultHandler);
            this.register(162105, ResOthersHiddenWeaponInfoMessage, ResOthersHiddenWeaponInfoHandler);
            this.register(162106, ResHiddenWeaponErrorMessage, ResHiddenWeaponErrorHandler);
            this.register(100314, ResRolesCreateReportToGateMessage, ResRolesCreateReportToGateMessageHandler);
            this.register(107201, StudySkillMessage, StudySkillHandle);
            this.register(103891, ResChangeOneAttributeMessage, ResAddPointHandler);
            this.register(502101, ResFightPostionBroadcastMessage, ResFightPostionBroadcastHandler);
            this.register(510102, ResSummonPetAddMessage, ResSummonPetAddHandler);
            this.register(510106, ResSummonPetDieMessage, ResSummonPetDieHandler);
            this.register(501108, ResRoundSummonPetDisappearMessage, ResRoundSummonPetDisappearHandler);
            this.register(501134, ResSummonPetTranMoveMessage, ResSummonPetTranMoveHandler);
            this.register(501104, ResRoundSummonPetMessage, ResRoundSummonPetHandler);
            this.register(501122, ResSummonPetRunPositionsMessage, ResSummonPetRunPositionsHandler);
            this.register(501121, ResSummonPetStopMessage, ResSummonPetStopHandler);
            this.register(510105, ResSummonPetAttributeChangeMessage, ResSummonPetAttributeChangeHandler);
            this.register(501109, ResSetSpecialPositionMessage, ResSetSpecialPositionHandler);
            this.register(528317, ResBuffAddMessage, ResBuffAddHandler);
            this.register(528319, ResClearZoneCDMessage, ResClearZoneCDHandler);
            this.register(112209, ResOpenStoreMessage, ResOpenStoreHandler);
            this.register(610001, ResPtMainMessage, ResPtMainHandler);
            this.register(528118, ResZoneTeamErroMessage, ResZoneTeamErroHandler);
            this.register(55001, ResCollectionRewardMessage, ResCollectionRewardHandler);
            this.register(600000, ResTowerRewardSurplusMessage, ResTowerRewardSurplusHandler);
            this.register(600001, ResTowerIndexMessage, ResTowerIndexHandler);
            this.register(600002, ResTowerNextLvMessage, ResTowerNextLvHandler);
            this.register(600007, ResLostSkillInfosMessage, ResLostSkillInfosHandler);
            this.register(600008, ResActivateLostSkillMessage, ResActivateLostSkillHandler);
            this.register(600011, ResSpiritChangeMessage, ResSpiritChangeHandler);
            this.register(550101, ResCsysTopListMessage, ResCsysTopListHandler);
            this.register(550102, ResChangeIntegralMessage, ResChangeIntegralHandler);
            this.register(550105, ResPlayerKillMessage, ResPlayerKillHandler);
            this.register(550103, ResEnterActivitieMessage, ResEnterActivitieHandler);
            this.register(600203, ResTowerRewardMessage, ResTowerRewardHandler);
            this.register(550106, ResCsysEndMessage, ResCsysEndHandler);
            this.register(601100, ResFlashMoveMessage, ResFlashMoveHandler);
            this.register(512110, ResComboMessage, ResComboHandler);
            this.register(513003, ResSplitSuitMessage, ResSplitSuitHandler);
            this.register(543007, ResOpenPainMessage, ResOpenPainHandler);
            this.register(529122, ResGuildMemberListToKugooClientMessage, ResGuildMemberListToKugooClientHandler);
            this.register(529124, ResGuildBulletinToKugooClientMessage, ResGuildBulletinToKugooClientHandler);
            this.register(529125, ResGuildDeleteToKugooClientMessage, ResGuildDeleteToKugooClientHandler);
            this.register(529123, ResGuildLeaveToKugooClientMessage, ResGuildLeaveToKugooClientHandler);
            this.register(511010, ResAttributeChangeMessage, ResAttributeChangeHandler);
            this.register(543004, ResBossHomeDieMessage, ResBossHomeDieHandler);
            this.register(543003, ResBossHomePlayerNumMessage, ResBossHomePlayerNumHandler);
            this.register(543001, ResOpenBossHomeMessage, ResOpenBossHomeHandler);
            this.register(120202, ReqTaskFinshMessage, ReqTaskFinshHandler);
            this.register(120206, ReqQuickFinshMessage, ReqQuickFinshHandler);
            this.register(120203, ReqTaskUpAchieveMessage, ReqTaskUpAchieveHandler);
            this.register(120204, ReqTaskDownHardMessage, ReqTaskDownHardHandler);
            this.register(143203, ReqEpalaceTaskEndToGameMessage, ReqEpalaceTaskEndToGameHandler);
            this.register(120213, ReqConquerTaskQuckFinshMessage, ReqConquerTaskQuckFinshHandler);
            this.register(120208, ReqConquerTaskDevourMessage, ReqConquerTaskDevourHandler);
            this.register(120214, ReqRankTaskQuckFinshMessage, ReqRankTaskQuckFinshHandler);
            this.register(120215, ReqRankTaskQuckFinshAllMessage, ReqRankTaskQuckFinshAllHandler);
            this.register(131209, ResGetAssistantMessage, ResGetAssistantHander);
            this.register(600009, ResEventChanageToClientMessage, ResEventChanageToClientHandler);
            this.register(600105, ResGainBoxToClientMessage, ResGainBoxToClientHandler);
            this.register(600101, ResLivenessToClientMessage, ResLivenessToClientHandler);
            this.register(600107, ResGainStateToClientMessage, ResGainStateToClientHandler);
            this.register(600103, ResLivenessEventsToClientMessage, ResLivenessEventsToClientHandler);
            this.register(528332, ResPrayInfoMessage, ResPrayInfoHandler);
            this.register(528333, ResPrayResultToClientMessage, ResPrayResultToClientHandler);
            this.register(601001, ResFillSignSucceedMessage, ResFillSignSucceedHandler);
            this.register(600012, ResReceiveAwardsMessage, ResReceiveAwardsHandler);
            this.register(120119, ResGetGuidesMessage, ResGuideInfoHandler);
            this.register(128101, ResZonePanelSelectMessage, ResZonePanelSelectHandler);
            this.register(130205, ResStrengthEffectMessage, ResStrengthEffectHandler);
            this.register(542102, ResWingChangeMessage, ResWingChangeHandler);
            this.register(542103, ResStrengthLevelMessage, ResStrengthLevelHandler);
            this.register(120219, ResTaskRewardInBagMessage, ResTaskRewardInBagHandler);
            this.register(528101, ResOpenGoldRaffleInfoToClientMessage, ResOpenGoldRaffleInfoToClientHandler);
            this.register(528102, ResGoldRaffleToClientMessage, ResGoldRaffleToClientHandler);
            this.register(528104, ResOpenGoldRaffleBoxInfoToClientMessage, ResOpenGoldRaffleBoxInfoToClientHandler);
            this.register(528106, ResFractionToClientMessage, ResFractionToClientHandler);
            this.register(528105, ResGoldRaffleBoxUseItemToClientMessage, ResGoldRaffleBoxUseItemToClientHandler);
            this.register(528103, ResGoldRaffleEventInfoToClientMessage, ResGoldRaffleEventInfoToClientHandler);
            this.register(510200, ResQueryBankMessage, ResQueryBankMessageToClientHandler);
            this.register(510202, ResQueryBankLogMessage, ResQueryBankLogMessageToClientHandler);
            this.register(600004, ResGradeGiftMessage, ResGradeGiftHandler);
            this.register(600005, ResGradeGiftInfoMessage, ResGradeGiftInfoHandler);
            this.register(600006, ResGainGradeGiftInfoMessage, ResGainGradeGiftInfoHandler);
            this.register(510020, ResBossEventMessage, ResBossEventHandler);
            this.register(510021, ResBossKillMessage, ResBossKillHandler);
            this.register(529101, ResCastingOpenToClientMessage, ResCastingOpenToClientHandler);
            this.register(529102, ResCastingRewardToClientMessage, ResCastingRewardToClientHandler);
            this.register(529103, ResCastingUseItemToClientMessage, ResCastingUseItemToClientHandler);
            this.register(529104, ResCastingDecomposeToClientMessage, ResCastingDecomposeToClientHandler);
            this.register(529105, ResCastingSellToClientMessage, ResCastingSellToClientHandler);
            this.register(529106, ResCastingExchangeToClientMessage, ResCastingExchangeToClientHandler);
            this.register(511000, ResNewActivityList, ResNewActivityListHandler);
            this.register(511002, ResGetNewActivityInfo, ResGetNewActivityInfoHandler);
            this.register(511004, ResGetNewActivityAward, ResGetNewActivityAwardHandler);
            this.register(511006, ResGetPlatformGiftError, ResGetPlatformGiftErrorHandler);
            this.register(511007, ResGetRankInfoMessage, ResGetRankInfoMessageHandler);
            this.register(511008, ResAddActivityMessage, ResAddActivityMessageHandler);
            this.register(511009, ResRemoveActivityMessage, ResRemoveActivityMessageHandler);
            this.register(511400, ResPlayerPkValueChangeMessage, ResPlayerPKValueChangeHandler);
            this.register(511401, ResChangePlayerEnemiesToClientMessage, ResPlayerEnemiesChangeHandler);
            this.register(106203, ResEquipTimeLostMessage, ResEquipTimeLostHandler);
            this.register(511011, ResRoundChangeJobMessage, ResRoundChangeJobHandler);
            this.register(511012, ResPushArtifactInfoMessage, ResPushArtifactInfoHandler);
            this.register(511014, ResExtractArtifactMessage, ResExtractArtifactHandler);
            this.register(511016, ResRemoldArtifactMessage, ResRemoldArtifactHandler);
            this.register(600015, ResOpenIconMessage, ResOpenIconHandler);
            this.register(600016, ResHideIconMessage, ResHideIconHandler);
            this.register(600017, ResSneakMessage, ResSneakHandler);
            this.register(600018, ResSpecialMessage, ResWolfSpecialHandler);
            this.register(600019, ResNpcBloodMessage, ResNPCBloodHandler);
            this.register(600020, ResStepMessage, ResWolfSoulStepHandler);
            this.register(600021, ResNpcBuffMessage, ResWolfSoulNpcBuffHandler);
            this.register(512005, ResQuryItemsMessage, ResAuctionOpenUpHandler);
            this.register(512007, ResQuryMyItemsMessage, ResSelfAuctionHandler);
            this.register(512009, ResAuctionShowItemMessage, ResAuctionShowHandler);
            this.register(512010, ResAuctionBuyfinshMessage, ResAuctionBuyHandler);
            this.register(504000, ResMapBossInfoMessage, ResMapBossInfoHandler);
            this.register(529107, ResPlayerTitleInfoToClientMessage, ResPlayerTitleInfoToClientHandler);
            this.register(529108, ResPlayerTitleListInfoToClientMessage, ResPlayerTitleListInfoToClientHandler);
            this.register(529110, ResPlayerTitleChangeMessage, ResPlayerTitleChangeHandler);
            this.register(529109, ResPlayerTitleNotifysToClientMessage, ResPlayerTitleNotifysToClientHandler);
            this.register(164101, ResAskedPanelToClientMessage, ResAskedPanelToClientHandler);
            this.register(164102, ResPointToClientMessage, ResPointToClientHandler);
            this.register(600022, ResProtectStateMessage, ResProtectStateHandler);
            this.register(164103, ResVerificationMessage, ResVerificationHandler);
            this.register(116005, ResRenewProtectMessage, ResRenewProtectHandler);
            this.register(513001, ResConvertSuitMessage, ResConvertSuitHandler);
            this.register(513002, ResSuitEffectMessage, ResSuitEffectHandler);
            this.register(107006, ResEquipChangeMessage, EquipChangeHandler);
            this.register(601101, ResDamageResultMessage, ResDamageResultHandler);
            this.register(600023, ResWorldLevelMessage, ResWorldLevelHandler);
            this.register(600024, ResWorldLevelInfoMessage, ResWorldLevelInfoHandler);
            this.register(563001, ResGetSuperVipInfoMessage, ResGetSuperVipInfoHandler);
            this.register(529112, ResCloudBuyToClientMessage, ResCloudBuyHandler);
            this.register(529111, ResOpenCloudBuyInfoToClientMessage, ResOpenCloudBuyInfoHandler);
            this.register(529113, ResRewardToClientMessage, ResRewardToClientHandler);
            this.register(529114, ResUpdateCloudBuyToClientMessage, ResUpdateCloudBuyHandler);
            this.register(529115, ResLoginCloudBuyInfoToClientMessage, ResLoginCloudBuyInfoToClientHandler);
            this.register(541333, ResNeedItemMessage, ResNeedItemHandler);
            this.register(511019, ResExchangeJewewlryMessage, ResExchangeJewewlryHandler);
            this.register(120020, ResFinishThreeChangeJobMessage, ResFinishThreeChangeJobHandler);
            this.register(529120, ResGuildImpeachToClientMessage, ResGuildImpeachToClientHandler);
            this.register(529121, ResGuildImpeachInfoToClientMessage, resGuildImpeachInfoToClientHandler);
            this.register(600025, ResGMOpenIconMessage, ResGMOpenIconHandler);
            this.register(511020, ResFirstPayGroupCountMessage, ResFirstPayGroupCountHandler);
            this.register(575001, ResGetActivatedStarInfo, ResGetActivatedStarInfoHandler);
            this.register(575003, ResIsActivateSuccese, ResIsActivateSucceseHandler);
            this.register(504100, ResMasterSkillInfosMessage, ResMasterSkillInfosHandler);
            this.register(504102, ResModifyMasterSkillMessage, ResModifyMasterSkillHandler);
            this.register(504104, ResMasterSkillResetMessage, ResMasterSkillResetHandler);
            this.register(504105, ResSyncMasterSkillPointMessage, ResSyncMasterSkillPointHandler);
            this.register(504106, ResModifySkillCDTimeMessage, ResModifySkillCDTimeHandler);
            this.register(504107, ResResetAllSkillCDTime, ResResetAllSkillCDTimeHandler);
            this.register(504108, ResTouchMasterSkillMessage, ResTouchMasterSkillHandler);
            this.register(504109, ResImmuneBuffMessage, ResImmuneBuffHandler);
            this.register(600026, ResMagicbookLevelMessage, ResMagicbookLevelHandler);
            this.register(600027, ResSeeOtherMagicbookMessage, ResSeeOtherMagicbookHandler);
            this.register(600028, ResMagicbookMessage, ResMagicbookHandler);
            this.register(600029, ResUseOnceMessage, ResUseOnceHandler);
            this.register(600030, ResExpMessage, ResExpHandler);
            this.register(600031, ResBreakthroughMessage, ResBreakthroughHandler);
            this.register(600032, ResAttrsMessage, ResAttrsHandler);
            this.register(600033, ResSkillsMessage, ResSkillsHandler);
            this.register(600034, ResMagicbookAttacklMessage, ResMagicbookAttacklHandler);
            this.register(600035, ResBeAttackInfoMessage, ResBeAttackInfoHandler);
            this.register(600036, ResBookGainStateMessage, ResBookGainStateHandler);
            this.register(600037, ResAdvancedUpMessage, ResAdvancedUpHandler);
            this.register(600038, ResGainBookMessage, ResGainBookHandler);
            this.register(505001, ResDropPlayerIntoBlackRoomMessage, ResDropPlayerIntoBlackRoomHandler);
            this.register(529117, ResSubmitImproveDataMessage, ResSubmitImproveDataHandler);
            this.register(600039, ResProtectItemMessage, ResProtectItemHandler);
            this.register(600040, ResProtectMessage, ResProtectHandler);
            this.register(505010, ResResponseBossDamageMessage, BossDamageRankHandler);
            this.register(600041, ResEheartInfoMessage, ResEheartInfoHandler);
            this.register(600042, ResRemoveMessage, ResRemoveHandler);
            this.register(600043, ResAddMessage, ResAddHandler);
            this.register(600044, ResElementValueMessage, ResElementValueHandler);
            this.register(600045, ResLockMessage, ResLockHandler);
            this.register(600046, ResUpdateMessage, ResUpdateHandler);
            this.register(529119, ResOpenBoCakeInfoToClientMessage, ResDiceResultHandler);
            return;
        }// end function

        private function register(param1:int, param2:Class, param3:Class) : void
        {
            this.messages[param1] = param2;
            this.handlers[param1] = param3;
            return;
        }// end function

        public function getMessage(param1:int) : Message
        {
            if (this.messages[param1] == null)
            {
                return null;
            }
            return new this.messages[param1] as Message;
        }// end function

        public function getHandler(param1:int) : Handler
        {
            if (this.handlers[param1] == null)
            {
                return null;
            }
            return new this.handlers[param1] as Handler;
        }// end function

    }
}
